language: cpp
#ubuntu 20.04
dist: focal
addons:
  apt:
    sources:
    # add PPAs with more up-to-date toolchains
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-10
    packages:
    # install toolchains
    - gcc-5
    - g++-5
    - clang-11
jobs:
  include:
    - os: linux
      arch: arm64
      env: OS=arm64_linux
    - os: linux
      arch: amd64
      env: OS=amd64_linux
      before_install:
        - sudo apt-get update
        - sudo apt-get install cmake
        - sudo apt-get install openssl
        - sudo apt-get install libssl-dev

script:
  - if [ -e /usr/lib/libuWs.so ];then
    sudo rm /usr/lib/libuWs.so;
    fi
  - ./install-ubuntu.sh
  - mkdir build
  - cd build
  - cmake .. && make