language: cpp
dist: bionic
addons:
  apt:
    sources:
    # add PPAs with more up-to-date toolchains
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.6
    packages:
    # install toolchains
    - gcc-5
    - g++-5
    - clang-3.6
jobs:
  include:
    - os: linux
      arch: arm64
      env: OS=arm64_linux
    - os: linux
      arch: amd64
      env: OS=amd64_linux
    - os: windows
      arch: amd64
      env: OS=windows
    - os: osx
      arch: amd64
      env: OS=osx
      before_install:
        - sudo dpkg --add-architecture armhf
        - sudo apt-get update
        - sudo apt-get install crossbuild-essential-armhf libc6:armhf libstdc++6:armhf
        - sudo apt-get install cmake
        - sudo apt-get install openssl
        - sudo apt-get install libssl-dev
        - sudo rm /usr/lib/libuWs.so
        - ./install-ubuntu.sh
script:
  - mkdir build
  - cd build
  - if [[ ${TRAVIS_OS_NAME} == "windows" ]]; then
        cmake ..
        cmake --build . --config release
    else
        cmake .. && make